backend/app/urls.py
from django.urls import include, path

import hr.urls

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include(hr.urls)),
]

backend/hr/urls.py
from django.urls import path

from . import views

app_name = "hr"


urlpatterns = [
    path("", views.index, name="index"),
    path("reset_db", views.reset_db, name="reset_db"),
    path("add_employee", views.add_employee, name="add_employee"),
    path("employees", views.employees, name="employees"),
    path("employee/<id>/address", views.address, name="address"),
    path("employee/<id>/basic", views.basic, name="basic"),
    path("employee/<id>/legal", views.legal, name="legal"),
    path("employee/<id>", views.employee, name="employee"),
    path("employee/delete/<id>", views.delete_employee, name="delete_employee"),
    path("employee/<id>/promote", views.promote, name="promote"),
    path("employee/<id>/add_to_team", views.add_to_team, name="add_to_team"),
    path("teams", views.teams, name="teams"),
    path("add_team", views.add_team, name="add_team"),
    path("team/<id>", views.team, name="team"),
    path("team/delete/<id>", views.delete_team, name="delete_team"),
    path("team/<id>/members", views.members, name="members"),
]

backend/hr/models.py
from django.db import models


class BasicInfo(models.Model):
    name = models.CharField(null=False, max_length=100)
    email = models.EmailField(null=False)
    address_line1 = models.CharField(null=False, max_length=100)
    address_line2 = models.CharField(null=False, max_length=100)
    city = models.CharField(null=False, max_length=100)
    zip_code = models.CharField(null=False, max_length=100)

    def __str__(self):
        return f"{self.name} - {self.email}"


class Contract(models.Model):
    hiring_date = models.CharField(null=False, max_length=30)
    job_title = models.CharField(null=False, max_length=100)

    def __str__(self):
        return f"{self.job_title} - hired on {self.hiring_date}"


class Team(models.Model):
    name = models.CharField(null=False, max_length=100)

    def __str__(self):
        return f"{self.name} # {self.id}"


class Employee(models.Model):
    basic_info = models.OneToOneField(BasicInfo, null=False, on_delete=models.CASCADE)
    contract = models.OneToOneField(Contract, null=False, on_delete=models.CASCADE)
    manager = models.ForeignKey("self", on_delete=models.SET_NULL, null=True)
    is_manager = models.BooleanField(default=False)
    team = models.ForeignKey(Team, null=True, on_delete=models.CASCADE)

    def __str__(self):
        res = self.basic_info.name
        if self.is_manager:
            res += " (manager)"
        return res

backend/hr/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render

from .models import BasicInfo, Contract, Employee, Team


def index(request):
    return render(request, "hr/index.html")


def reset_db(request):
    if request.method == "GET":
        return render(request, "hr/reset_db.html")
    else:
        BasicInfo.objects.all().delete()
        Contract.objects.all().delete()
        Employee.objects.all().delete()
        Team.objects.all().delete()
        return redirect("hr:index")


def employees(request):
    return render(
        request,
        "hr/employees.html",
        context={"employees": Employee.objects.all()},
    )


def employee(request, id):
    employee = get_object_or_404(Employee, pk=id)
    context = {"employee": employee}
    return render(request, "hr/employee.html", context=context)


def delete_employee(request, id):
    employee = get_object_or_404(Employee, pk=id)
    if request.method == "GET":
        context = {"employee": employee}
        return render(request, "hr/delete_employee.html", context=context)
    else:
        employee.delete()
        return redirect("hr:employees")


def add_employee(request):
    if request.method == "GET":
        return render(request, "hr/add_employee.html")
    else:
        payload = request.POST
        errors = False

        # Basic
        basic_keys = [
            "name",
            "email",
        ]
        basic_params = {}
        for key in basic_keys:
            value = payload.get(key)
            if value is not None:
                if value:
                    basic_params[key] = value
                else:
                    messages.add_message(
                        request, messages.ERROR, f"{key} cannot be blank"
                    )
                    errors = True

        # Address
        address_keys = [
            "address_line1",
            "address_line2",
            "city",
            "zip_code",
        ]
        address_params = {}
        for key in address_keys:
            value = payload.get(key)
            if value is not None:
                if value:
                    address_params[key] = value
                    if key == "zip_code":
                        try:
                            int(value)
                        except ValueError:
                            messages.add_message(
                                request, messages.ERROR, "zip_code must be an int"
                            )
                            errors = True
                else:
                    messages.add_message(
                        request, messages.ERROR, f"{key} cannot be blank"
                    )
                    errors = True

        # Legal
        contract_keys = [
            "hiring_date",
            "job_title",
        ]
        contract_params = {}
        for key in contract_keys:
            value = payload.get(key)
            if value is not None:
                if value:
                    contract_params[key] = value
                else:
                    messages.add_message(
                        request, messages.ERROR, f"{key} cannot be blank"
                    )
                    errors = True

        if errors:
            employee = {
                "name": basic_params.get("name", ""),
                "email": basic_params.get("email", ""),
                "basic_info": address_params,
                "contract": contract_params,
            }
            context = {"employee": employee}
            print(context)
            return render(request, "hr/add_employee.html", context)
        else:
            basic_info = BasicInfo.objects.create(**basic_params, **address_params)
            contract = Contract.objects.create(**contract_params)
            Employee.objects.create(basic_info=basic_info, contract=contract)
        return redirect("hr:employees")


def address(request, id):
    employee = get_object_or_404(Employee, pk=id)
    context = {"employee": employee}
    if request.method == "POST":
        return update_address(request, employee)
    else:
        return render(request, "hr/address.html", context=context)


def basic(request, id):
    employee = get_object_or_404(Employee, pk=id)
    context = {"employee": employee}
    if request.method == "POST":
        return update_basic(request, employee)
    else:
        return render(request, "hr/basic.html", context=context)


def legal(request, id):
    employee = get_object_or_404(Employee, pk=id)
    context = {"employee": employee}
    if request.method == "POST":
        return update_legal(request, employee)
    else:
        return render(request, "hr/legal.html", context=context)


def update_address(request, employee):
    payload = request.POST
    errors = False
    basic_info = employee.basic_info
    for key in [
        "address_line1",
        "address_line2",
        "city",
        "zip_code",
    ]:
        value = payload.get(key)
        if value is not None:
            if value:
                if key == "zip_code":
                    try:
                        int(value)
                        setattr(basic_info, key, value)
                    except ValueError:
                        messages.add_message(
                            request, messages.ERROR, "zip_code must be an int"
                        )
                        errors = True
                else:
                    setattr(basic_info, key, value)
            else:
                messages.add_message(request, messages.ERROR, f"{key} cannot be blank")
                errors = True
    if errors:
        context = {"employee": employee}
        return render(request, "hr/basic.html", context=context)
    else:
        basic_info.save()
        return redirect("hr:employees")


def update_basic(request, employee):
    payload = request.POST
    errors = False
    keys = ["name", "email"]
    basic_info = employee.basic_info
    for key in keys:
        value = payload.get(key)
        if value is not None:
            if value:
                setattr(basic_info, key, value)
            else:
                messages.add_message(request, messages.ERROR, f"{key} cannot be blank")
                errors = True
    if errors:
        context = {"employee": employee}
        return render(request, "hr/basic.html", context=context)
    else:
        basic_info.save()
        return redirect("hr:employees")


def update_legal(request, employee):
    payload = request.POST
    errors = False
    contract = employee.contract
    for key in [
        "job_title",
        "hiring_date",
    ]:
        value = payload.get(key)
        if value is not None:
            if value:
                setattr(contract, key, value)
            else:
                messages.add_message(request, messages.ERROR, f"{key} cannot be blank")
                errors = True
    if errors:
        context = {"employee": employee}
        return render(request, "hr/legal.html", context=context)
    else:
        contract.save()
        return redirect("hr:employees")


def promote(request, id):
    employee = get_object_or_404(Employee, pk=id)
    context = {"employee": employee}
    if request.method == "POST":
        return promote_employee(request, employee)
    else:
        return render(request, "hr/promote.html", context=context)


def promote_employee(request, employee):
    employee.is_manager = True
    employee.save()
    return redirect("hr:employees")


def teams(request):
    return render(
        request,
        "hr/teams.html",
        context={"teams": Team.objects.all()},
    )


def add_team(request):
    if request.method == "POST":
        payload = request.POST
        errors = False
        creation_params = {}
        for key in [
            "name",
        ]:
            value = payload.get(key)
            if value is not None:
                if value:
                    creation_params[key] = value
                else:
                    messages.add_message(
                        request, messages.ERROR, f"{key} cannot be blank"
                    )
                    errors = True
        if errors:
            context = {"team": creation_params}
            return render(request, "hr/add_team", context=context)
        else:
            team = Team.objects.create(**creation_params)
            team.save()
            return redirect("hr:teams")
    else:
        return render(
            request,
            "hr/add_team.html",
        )


def team(request, id):
    team = get_object_or_404(Team, pk=id)
    return render(
        request,
        "hr/team.html",
        context={"team": team},
    )


def members(request, id):
    team = get_object_or_404(Team, pk=id)
    members = Employee.objects.filter(team=team)
    return render(
        request,
        "hr/members.html",
        context={"team": team, "members": members},
    )


def delete_team(request, id):
    team = get_object_or_404(Team, pk=id)
    if request.method == "GET":
        return render(
            request,
            "hr/delete_team.html",
            context={"team": team},
        )
    else:
        team.delete()
        return redirect("hr:teams")


def add_to_team(request, id):
    employee = get_object_or_404(Employee, pk=id)
    teams = Team.objects.all()
    context = {
        "employee": employee,
        "teams": teams,
    }
    if request.method == "GET":
        return render(request, "hr/add_to_team.html", context=context)
    else:
        team_id = request.POST.get("team_id")
        if not team_id:
            messages.add_message(request, messages.ERROR, "Please select a team")
            return render(request, "hr/add_to_team.html", context=context)
        try:
            team = Team.objects.get(pk=team_id)
        except (Team.DoesNotExist, ValueError):

backend/templates/hr/add_employee.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Add Employee
{% endblock %}
{% block content %}
{% if messages %}
<strong>Error</strong>
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<h2>Add new employee</h2>
<form method="post" action="{% url 'hr:add_employee' %}">
  {% csrf_token %}

  {% component "basic_info" employee %}
  {% component "address"  employee %}
  {% component "legal" employee %}

  <button type="submit" class="btn btn-primary">Add</button>
</form>
{% endblock %}

backend/templates/hr/add_team.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Add Team
{% endblock %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<h2>Create new team</h2>
<form method="post" action="{% url 'hr:add_team' %}">
  {% csrf_token %}

  <div class="row">
    <div class="col">
      <label for="name" class="form-label">Name</label>
    </div>
    <div class="col col-10">
      <input class="form-control" name="name" value="{{ team.name }}" />
    </div>
  </div>


  <button type="submit" class="btn btn-primary">Add</button>
</form>
{% endblock %}

backend/templates/hr/add_to_team.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Add Team
{% endblock %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<h2>Add new member to existing team</h2>
Name: {{ employee.basic_info.name }}
<form method="post" action="{% url 'hr:add_to_team' employee.id %}">
  {% csrf_token %}

    <div class="form-group col-md-4">
      <label for="inputState">Team</label>
      <select name="team_id" class="form-control">
        <option selected>Choose ...</option>
        {% for team in teams %}
        <option value="{{ team.id }}">{{ team.name }}</option>
        {% endfor %}
      </select>
    </div>

  <button type="submit" class="btn btn-primary">Add</button>
</form>
{% endblock %}

backend/templates/hr/address.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Edit d Address
{% endblock %}
{% block content %}
<h2>Edit Address</h2>
Editing address of {{ employee.basic_info.name }}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="{% url 'hr:address'  employee.id %}" method="post">
  {% csrf_token %}
  {% component "address" employee=employee %}

  <button type="submit" class="btn btn-primary">Update</button>
</form>
{% endblock %}

backend/templates/hr/basic.html
{% extends 'hr/base.html' %}
{% block title %}
HR Manager - Edit basic Information
{% endblock %}
{% block content %}
<h2>Edit Employee Basic Information</h2>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="{% url 'hr:basic' employee.id %}" method='post'>
  {% csrf_token %}
  {% component "basic_info" employee.basic_info %}
  <button type="submit" class="btn btn-primary">Update</button>
</form>
{% endblock %}

backend/templates/hr/delete_employee.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Delete Employee
{% endblock %}
{% block content %}
<h2> Delete Employee </h2>
<p>
  You are about to delete records about <br />
  name: {{ employee.basic_info.name }} <br />
  email: {{ employee.basic_info.email }} <br />
</p>
<p>This cannot be undone.</p>
<form method="post" action="{% url 'hr:delete_employee' employee.id %}" >
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Proceed</button>
</form>
{% endblock %}

backend/templates/hr/delete_team.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Delete Team
{% endblock %}
{% block content %}
<h2> Delete Team </h2>
<p>
  You are about to delete the team {{ team.name }}
</p>
<p>This cannot be undone.</p>
<form method="post" action="{% url 'hr:delete_team' team.id %}" >
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Proceed</button>
</form>
{% endblock %}

backend/templates/hr/employee.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Employees
{% endblock %}
{% block content %}
<h2>Edit Employee</h2>
<p>{{ employee.basic_info.name }} - {{ employee.basic_info.email }}</p>
<p>{{ employee.contract.job_title }}
<p>Hired on {{ employee.contract.hiring_date }}</p>
<ul>
  <li>
    <a href='{% url 'hr:basic' employee.id %}'> Update basic info </a>
  </li>
  <li>
    <a href='{% url 'hr:address' employee.id %}'> Update address </a>
  </li>
  <li>
    <a href='{% url 'hr:legal' employee.id %}'> Update legal info </a>
  </li>
  <li>
    <a href='{% url 'hr:promote' employee.id %}'>Promote as manager</a>
  </li>
  <li>
    <a href='{% url 'hr:add_to_team' employee.id %}'>Add to team</a>
  </li>
</ul>

{% endblock %}

backend/templates/hr/employees.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Employees
{% endblock %}
{% block content %}
<h2>Employees ({{ employees| length }})</h2>
{% if employees %}
<table class="table">
  <thead>
    <tr>
      <th>name</th>
      <th>email</th>
      <th>manager?<th/>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employees %}
    <tr>
      <td>{{ employee.basic_info.name }}</td>
      <td>{{ employee.basic_info.email }}</td>
      <td>
        {% if employee.is_manager %}
        <strong>yes</strong>
        {%  else %}
        no
        {% endif %}
        </td>
      <td>
        <a href="{% url 'hr:employee' employee.id %}" class="btn btn-primary">
          Edit
        </a>
      </td>
      <td>
        <a href="{% url 'hr:delete_employee' employee.id %}" class="btn btn-danger">
          Delete
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
No employees yet
{% endif %}
{% endblock %}

backend/templates/hr/index.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB
{% endblock %}
{% block content %}
<h1 id='title'>HR DB</h1>
<h2>Employees</h2>
<ul>
  <li><a href="{% url 'hr:employees' %}">List Employees</a></li>
  <li><a href="{% url 'hr:add_employee' %}">Add new employee</a></li>
</ul>
<h2>Teams</h2>
<ul>
  <li><a href="{% url 'hr:teams' %}">List teams</a></li>
  <li><a href="{% url 'hr:add_team' %}">Create new team</a></li>
</ul>
<h2> Danger zone </h2>
<ul>
  <li><a href="{% url 'hr:reset_db' %}">Reset database</a></li>
</ul>
{% endblock %}

backend/templates/hr/legal.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Edit Legal Information
{% endblock %}
{% block content %}
<h2>Edit Employee Legal Information</h2>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="{% url 'hr:legal' employee.id %}" method='post'>
  {% csrf_token %}
  {% component "legal" employee=employee %}
  <button type="submit" class="btn btn-primary">Update</button>
</form>
{% endblock %}

backend/templates/hr/members.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Team members
{% endblock %}
{% block content %}
<h2>Team Members</h2>
<p>
Name: {{ team.name }}
</p>

<p>
<ul>
{% for member in members %}
  <li>{{ member.basic_info.name }}
  {% if member.is_manager %}
  <strong>(manager)</strong>
  {% endif %}
  </li>

{% empty %}
</u>
This team has no members
{% endfor %}
</p>

{% endblock %}

backend/templates/hr/promote.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Promote Employee
{% endblock %}
{% block content %}
<h2>Promote employee</h2>
<p>{{ employee.basic_info.name }} is going to be promoted as a manager</p>
<form action="{% url 'hr:promote' employee.id %}" method='post'>
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">Proceed</button>
</form>
{% endblock %}

backend/templates/hr/reset_db.html
{% extends 'hr/base.html' %}
{% block title %}
HR DB - Reset database
{% endblock %}
{% block content %}
<h2> Reset Database </h2>
<p>
  You are about to delete all the information from the database.
</p>
<p>This cannot be undone.</p>
<form method="post" action="{% url 'hr:reset_db' %}" >
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Proceed</button>
</form>
{% endblock %}